# Problem 1

In [1]:
import numpy as np

In [2]:
array = np.random.randint(1,50,size=(5,4))
print(array)

[[19  1 12 37]
 [31 11 40  9]
 [31 22 20 48]
 [11 15 13 47]
 [13 38 32 27]]


In [3]:
rows = 5
cols = 4
for col_start in range(cols - 1, -1, -1):
    i = 0
    j = col_start
    while i < rows and j < cols:
        print(array[i][j], end=' ')
        i += 1
        j += 1
    print()

# Bottom half diagonals (starting from row 1 to last row, leftmost column)
for row_start in range(1, rows):
    i = row_start
    j = 0
    while i < rows and j < cols:
        print(array[i][j], end=' ')
        i += 1
        j += 1
    print()

37 
12 9 
1 40 48 
19 11 20 47 
31 22 13 27 
31 15 32 
11 38 
13 


In [4]:
for i in range(rows):
    print(np.max(array[i]))

37
40
48
47
38


In [5]:
amean = np.mean(array)
print(amean)

23.85


In [6]:
arrnew = np.random.randint(1, amean, size=(5,4))
print(arrnew)

[[22  5 17 19]
 [19 11 20  9]
 [18  2 12  3]
 [ 2  1 19 22]
 [19 20 21 20]]


In [7]:
def numpy_boundary_traversal(matrix):
    rows, cols = matrix.shape
    result = []

    for i in range(cols):
        result.append(matrix[0][i])
    for i in range(1, rows):
        result.append(matrix[i][cols - 1])
    if rows > 1:
        for i in range(cols - 2, -1, -1):
            result.append(matrix[rows - 1][i])
    if cols > 1:
        for i in range(rows - 2, 0, -1):
            result.append(matrix[i][0])
    
    return result

In [8]:
numpy_boundary_traversal(array)

[19, 1, 12, 37, 9, 48, 47, 27, 32, 38, 13, 11, 31, 31]

# Problem 2

In [9]:
arrf = np.random.uniform(0, 10, size=20)
print(arrf)

[7.89223534 2.90744629 8.21843972 0.16074115 4.58818088 1.5009544
 4.92712912 6.95896072 6.48104213 2.50822803 8.07029993 4.90712753
 4.9997606  2.98858816 0.2537021  0.54755868 5.7952182  4.52156659
 0.58314151 0.91378386]


In [10]:
roundarr= np.round(arrf,2)
print(roundarr)

[7.89 2.91 8.22 0.16 4.59 1.5  4.93 6.96 6.48 2.51 8.07 4.91 5.   2.99
 0.25 0.55 5.8  4.52 0.58 0.91]


In [11]:
print(np.round(np.min(roundarr),2))
print(np.round(np.max(roundarr),2))
print(np.round(np.median(roundarr),2))

0.16
8.22
4.56


In [12]:
for idx in range(len(roundarr)):
    if roundarr[idx] < 5:
        roundarr[idx] = (roundarr[idx]*roundarr[idx])
print(np.round(roundarr,2))

[ 7.89  8.47  8.22  0.03 21.07  2.25 24.3   6.96  6.48  6.3   8.07 24.11
  5.    8.94  0.06  0.3   5.8  20.43  0.34  0.83]


In [13]:
import numpy as np

def numpy_alternate_sort(array):
    sortarr = np.sort(array)
    result = []

    left = 0
    right = len(sortarr) - 1

    while left <= right:
        result.append(sortarr[left])
        left += 1
        if left <= right:
            result.append(sortarr[right])
            right -= 1

    return np.array(result)

In [14]:
numpy_alternate_sort(roundarr)

array([ 0.0256, 24.3049,  0.0625, 24.1081,  0.3025, 21.0681,  0.3364,
       20.4304,  0.8281,  8.9401,  2.25  ,  8.4681,  5.    ,  8.22  ,
        5.8   ,  8.07  ,  6.3001,  7.89  ,  6.48  ,  6.96  ])

# Problem 3

In [15]:
import pandas as pd

In [16]:
names = ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Helen', 'Ivy', 'Jack']
subjects = ['Math', 'Science', 'Math', 'History', 'Science', 'Math', 'History', 'Math', 'Science', 'History']

# Random scores between 50 and 100
scores = np.random.randint(50, 101, size=10)

df = pd.DataFrame({
    'Name': names,
    'Subject': subjects,
    'Score': scores,
    'Grade': ''  # Initially empty
})
print(df)

      Name  Subject  Score Grade
0    Alice     Math     71      
1      Bob  Science     96      
2  Charlie     Math     52      
3    David  History     82      
4      Eva  Science     82      
5    Frank     Math     69      
6    Grace  History     53      
7    Helen     Math     99      
8      Ivy  Science     57      
9     Jack  History     55      


In [17]:
def assign_grade(score):
    if score >= 90:
        return 'A'
    elif score >= 80:
        return 'B'
    elif score >= 70:
        return 'C'
    elif score >= 60:
        return 'D'
    else:
        return 'F'

df['Grade'] = df['Score'].apply(assign_grade)
print(df)

      Name  Subject  Score Grade
0    Alice     Math     71     C
1      Bob  Science     96     A
2  Charlie     Math     52     F
3    David  History     82     B
4      Eva  Science     82     B
5    Frank     Math     69     D
6    Grace  History     53     F
7    Helen     Math     99     A
8      Ivy  Science     57     F
9     Jack  History     55     F


In [18]:
print("Sorted by Score (Descending):")
print(df.sort_values(by='Score', ascending=False), "\n")

Sorted by Score (Descending):
      Name  Subject  Score Grade
7    Helen     Math     99     A
1      Bob  Science     96     A
3    David  History     82     B
4      Eva  Science     82     B
0    Alice     Math     71     C
5    Frank     Math     69     D
8      Ivy  Science     57     F
9     Jack  History     55     F
6    Grace  History     53     F
2  Charlie     Math     52     F 



In [19]:
print("Average Score per Subject:")
print(df.groupby('Subject')['Score'].mean(), "\n")

Average Score per Subject:
Subject
History    63.333333
Math       72.750000
Science    78.333333
Name: Score, dtype: float64 



In [20]:
def pandas_filter_pass(dataframe):
    print(dataframe[dataframe['Grade'].isin(['A', 'B'])])


In [21]:
pandas_filter_pass(df)

    Name  Subject  Score Grade
1    Bob  Science     96     A
3  David  History     82     B
4    Eva  Science     82     B
7  Helen     Math     99     A


# Problem 4

In [22]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
import random

# 1. Generate synthetic reviews
positive_reviews = [
    "Absolutely loved it!", "Great acting and story.", "A masterpiece!", "Highly recommend this film.",
    "Fantastic direction and screenplay.", "Brilliantly done!", "Loved every minute.", "A delightful watch.",
    "Excellent plot and performance.", "Superb!", "Incredible movie.", "Really enjoyable.", "Heartwarming story.",
    "A beautiful film.", "So well made.", "Emotional and powerful.", "Perfectly crafted.", "Stunning visuals.",
    "Must watch!", "Top-notch.", "A classic!", "Five stars.", "Great film!", "Highly enjoyable.",
    "Great performances.", "Well-directed.", "Really good.", "Loved the message.", "Deeply moving.",
    "Absolutely perfect.", "Flawless execution.", "Enthralling movie.", "It was wonderful.",
    "Wonderful acting.", "Memorable experience.", "Captivating from start to finish.", "Truly inspiring.",
    "Well-paced and emotional.", "Left me speechless.", "Truly great cinema.", "Loved the characters.",
    "Beautifully written.", "Very well made.", "Well worth the time.", "Such a gem.",
    "A joy to watch.", "Breathtaking scenes.", "Simply amazing.", "It touched my heart.",
    "Impressive storytelling."
]

negative_reviews = [
    "Absolutely hated it.", "Terrible acting.", "Worst movie ever.", "Would not recommend.",
    "So boring.", "Waste of time.", "Poor direction.", "Horrible plot.", "Awful experience.",
    "Very disappointing.", "Fell asleep halfway.", "Nothing good here.", "Too slow and dull.",
    "Painful to watch.", "Zero stars.", "Plot made no sense.", "No character development.",
    "Terrible ending.", "Bad writing.", "Boring from start to end.", "Lacked emotion.",
    "Predictable and bland.", "Unwatchable.", "Disliked it totally.", "Complete disaster.",
    "Avoid at all costs.", "Too cliché.", "Low quality.", "Confusing and pointless.",
    "Ridiculous story.", "Weak performances.", "No real plot.", "Annoying soundtrack.",
    "Miserable film.", "Dragged too much.", "Was expecting more.", "Flat characters.",
    "Insult to cinema.", "Hated every minute.", "Regret watching.", "Uninspired film.",
    "Forgettable.", "Just bad.", "So unrealistic.", "Unbearable.", "Makes no sense.",
    "Fails on all fronts.", "Worst direction ever.", "Pathetic attempt.", "Didn't enjoy it at all."
]

In [23]:
print("Positive reviews:", len(positive_reviews))
print("Negative reviews:", len(negative_reviews))

Positive reviews: 50
Negative reviews: 50


In [24]:
# Combine and shuffle
reviews = positive_reviews + negative_reviews
sentiments = ['positive'] * 50 + ['negative'] * 50

In [25]:
data = pd.DataFrame({'Review': reviews, 'Sentiment': sentiments})
data = data.sample(frac=1, random_state=42).reset_index(drop=True)
print("\nStep 1: Combined Data Sample")
print(data.head())


Step 1: Combined Data Sample
                 Review Sentiment
0       Miserable film.  negative
1  Would not recommend.  negative
2       Lacked emotion.  negative
3       A joy to watch.  positive
4           Such a gem.  positive


In [26]:
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS
vectorizer = CountVectorizer(stop_words='english', max_features=500)
X = vectorizer.fit_transform(data['Review'])
y = data['Sentiment']
print("\nStep 2: Vectorized Feature Shape")
print(X.shape)


Step 2: Vectorized Feature Shape
(100, 135)


In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print("\nStep 3: Train/Test Sizes")
print("Train size:", X_train.shape[0])
print("Test size:", X_test.shape[0])


Step 3: Train/Test Sizes
Train size: 80
Test size: 20


In [28]:
model = MultinomialNB()
model.fit(X_train, y_train)
print("\nStep 4: Model Trained")


Step 4: Model Trained


In [29]:
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("\nStep 5: Test Accuracy")
print("Accuracy:", accuracy)


Step 5: Test Accuracy
Accuracy: 0.4


In [30]:
def predict_review_sentiment(model, vectorizer, review):
    tokens = vectorizer.transform([review])
    prediction = model.predict(tokens)
    return prediction[0]

In [31]:
sample = "The movie was really boring and disappointing."
print("\nPredicted Sentiment:", predict_review_sentiment(model, vectorizer, sample))


Predicted Sentiment: negative


# Problem 5

In [32]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

# Step 1: Create synthetic data
good_feedback = [
    "Loved the product", "Excellent quality", "Very satisfied", "Great value for money", "Works perfectly",
    "Super easy to use", "Exceeded expectations", "Highly recommend", "Fantastic experience", "Amazing results",
    "Perfect for daily use", "Very reliable", "Top-notch", "User-friendly design", "Exceptional performance",
    "Good build quality", "Efficient and fast", "Met all my needs", "Exactly what I wanted", "Would buy again",
    "Impressive durability", "Great packaging", "Comfortable to use", "Just awesome", "Very pleased",
    "Stunning product", "No complaints at all", "Looks premium", "Happy with my purchase", "Delivered quickly",
    "Beautiful design", "Solid and dependable", "Really convenient", "Everything was as described",
    "Better than expected", "Worth every penny", "Five stars", "Performs smoothly", "Feels high-end",
    "Reliable and affordable", "Love the features", "Crystal clear sound", "Sleek and modern", "Very useful",
    "Quick setup", "Compact and handy", "Nice finish", "Superb service", "No issues found", "Great for everyday use"
]
bad_feedback = [
    "Terrible quality", "Very disappointed", "Doesn't work", "Waste of money", "Too complicated",
    "Didn't meet expectations", "Wouldn't recommend", "Worst experience", "Poor results", "Completely useless",
    "Stopped working", "Unreliable product", "Faulty and cheap", "Horrible service", "Very confusing",
    "Feels flimsy", "Uncomfortable to use", "Not worth it", "Do not buy", "Regret this purchase",
    "Awful design", "Took forever to arrive", "Looks cheap", "Broke within a week", "No customer support",
    "Overpriced junk", "Too noisy", "Flawed performance", "Misleading description", "Poor packaging",
    "Unsatisfactory", "Setup was a nightmare", "Bad value", "Not user-friendly", "Very slow", "Completely broken",
    "Didn't last long", "Felt like a scam", "Low build quality", "Just terrible", "Returned it immediately",
    "Hated it", "Cracked on arrival", "Nothing good about it", "Very outdated", "Would give zero stars",
    "Feels cheap", "Lacks basic features", "Overheats quickly", "Wrong item received"
]

In [33]:
texts = good_feedback + bad_feedback
labels = ['good'] * 50 + ['bad'] * 50

df = pd.DataFrame({'Review': texts, 'Label': labels}).sample(frac=1, random_state=42).reset_index(drop=True)

print("Step 1: Data Sample")
print(df.head())

Step 1: Data Sample
              Review Label
0  Not user-friendly   bad
1     Waste of money   bad
2       Awful design   bad
3  Compact and handy  good
4        Quick setup  good


In [34]:
vectorizer = TfidfVectorizer(max_features=300, stop_words='english', lowercase=True)
X = vectorizer.fit_transform(df['Review'])
y = df['Label']

print("\nStep 2: Vectorized Shape")
print(X.shape)


Step 2: Vectorized Shape
(100, 149)


In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)
print("\nStep 3: Train/Test Split Sizes")
print("Train:", X_train.shape[0], "Test:", X_test.shape[0])


Step 3: Train/Test Split Sizes
Train: 75 Test: 25


In [36]:
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("\nStep 4: Classification Report")
print(classification_report(y_test, y_pred))


Step 4: Classification Report
              precision    recall  f1-score   support

         bad       0.30      0.88      0.45         8
        good       0.50      0.06      0.11        17

    accuracy                           0.32        25
   macro avg       0.40      0.47      0.28        25
weighted avg       0.44      0.32      0.22        25



In [37]:
def text_preprocess_vectorize(texts, vectorizer):
    return vectorizer.transform(texts)

In [38]:
sample_texts = ["Amazing product, very helpful", "Stopped working after two days"]
X_sample = text_preprocess_vectorize(sample_texts, vectorizer)
print("\nPredictions on sample inputs:")
print(model.predict(X_sample))


Predictions on sample inputs:
['good' 'bad']
